# Generated by Django 4.2.7 on 2023-11-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='HydJobs',
        ),
    ]
